version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    environment:
      - STAT_DB_URL=jdbc:postgresql://stat_server_db:5432/stats_db
      - STAT_DB_USER=sa
      - STAT_DB_PASSWORD=password
    depends_on:
      - stats-db

  stats-db:
    image: postgres:13.7-alpine
    container_name: stat_server_db
    ports:
      - "6062:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    environment:
      - MAIN_DB_URL=jdbc:postgresql://postgres-main-db:5432/ewm_db
      - MAIN_DB_USER=sa
      - MAIN_DB_PASSWORD=password
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:13.7-alpine
    container_name: postgres-main-db
    ports:
      - "6464:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password