version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - DB_HOST=stats-db
      - DB_PORT=5432
    depends_on:
      - stats-db

  stats-db:
    image: postgres:13.7-alpine

    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    environment:
      - EWM_STATS_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service
      - SPRING_DATASOURCE_USER=sa
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:15-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"

    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password